### PR TITLE
Generating printState function and trace calls only on --trace

### PR DESCRIPTION
**Pull request by frameworklabs**
Generating printState function and trace calls in app only when --trace option is given.

### CODE REVIEW

**Comment by FriedrichGretz** [comment]
Congrats on being the first to post a PR :-) It looks good. We will get back to you with technical feedback shortly.
Since we went online only recently we have lacked a contribution process. In fact a CLA based approach is currently under internal review. For the time being we resort to a simple DCO based process. Sorry about that... The details are in CONTRIBUTING.md. Essentially it says you should add yourself to the list of authors in NOTICE. And we can only accept commits that are signed with the "Signed-off-by  ..." line.
So when we agree that the PR is 100% fine, for example squash your commits into one that is signed.

**Comment by FriedrichGretz** [comment]
Now to the interesting bit :-)

Please add
`+ " --trace "`
in file test/testCodegeneration.fs after line 276
to reproduce the original behaviour.

Apart from this, everything works fine. Great job!

And just a minor comment. I'd suggest to rewrite the 
`<.> empty <.>`
construction in CodeGeneration.fs:381 as

    [ Comment.cTraceFunction
      traceFunctionPrototype]
    |> dpToplevel

to better express the intention.

I believe @schorg has another comment on dll versioning...

**Comment by schorg** [comment]
I will increase dll versioning after the merge. 

Currently Version handling is just too distributed over files and repositories.

**Comment by frameworklabs** [comment]
I am currently waiting on my employer to get the go for contributing to this project.
After that I plan to address issue #18

**Comment by FriedrichGretz** [comment]
... and it's merged. Thanks you very much for the contribution. Looking forward to more ;-)

**Comment by frameworklabs** [comment]
Thanks for merging!

Blech is a really exciting and profound project / technology - nice to be able to contribute to it.

**Pull request merged**
